// LOADING CONSTANTS
export const SET_LOADING = 'SET_LOADING';
export const CLEAR_LOADING = 'CLEAR_LOADING';

// MESSAGE/ERROR CONSTANTS
export const GET_MSG = 'GET_MSG';
export const GET_ERROR = 'GET_ERROR';
export const CLEAR_MSG = 'CLEAR_MSG';

// TASK CONSTANTS
export const GET_TASK_DETAIL_SUCCESS = 'GET_TASK_DETAIL_SUCCESS';
export const GET_USER_TASK_SUCCESS = 'GET_USER_TASK_SUCCESS';
